id: I3F3CC25C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T04:35:47+00:00'
last_modified: '2022-06-08T02:18:41.109485+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC426
  title: 'རྗེ་བཙུན་མར་པའི་རྣམ་པར་ཐར་པ་གྲུབ་པའི་ངོ་མཚར་བརྗོད་པ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A278:
      image_group_id: I2PD18865
      title: ''
      total_pages: 186
      order: 1
      base_file: A278.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
